{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-ami-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-ami-operator.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "eks-ami-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
{{- end }}