---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-eks-aws-harsh-dev-v1alpha1-nodegroupupgradepolicy
  failurePolicy: Fail
  name: vnodegroupupgradepolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - eks.aws.harsh.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodegroupupgradepolicies
  sideEffects: None
