---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - eks.aws.harsh.dev
  resources:
  - nodegroupupgradepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.aws.harsh.dev
  resources:
  - nodegroupupgradepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - eks.aws.harsh.dev
  resources:
  - nodegroupupgradepolicies/status
  verbs:
  - get
  - patch
  - update
